### ISSUE TITLE
request for improvement

### ISSUE THREAD

**Issue by sholoomail** [DeccanBotz/OCR#1]
hi.
can you replace ocr website with https://www.newocr.com/ or others that support more langs?
thanks.

**Comment by MJ8506** [comment]
Hello 
We will try our best to use (https://www.newocr.com/) to get more Languages support.
Thanks for your Issue

**Comment by DeccanBotz** [comment]
Hello @sholoomail,
We will try our best to use (https://www.newocr.com/) to get more Languages support.
Thanks for your Issue.
